import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{vue,ts}"],
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1d",
        background: "#f8f9fa",
        primary: "#004c4c",
        "primary-container": "#006666",
        "primary-fixed": "#a2f0ef",
        "primary-fixed-dim": "#86d4d3",
        "on-primary": "#ffffff",
        "on-primary-container": "#93e1e0",
        "on-primary-fixed": "#002020",
        "on-primary-fixed-variant": "#004f4f",
        secondary: "#904d00",
        "secondary-container": "#ffa454",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#713b00",
        surface: "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "surface-container": "#edeeef",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-variant": "#e1e3e4",
        outline: "#6f7979",
        "outline-variant": "#bec9c8",
        "on-surface": "#191c1d",
        "on-surface-variant": "#3f4948",
        "surface-tint": "#096969",
        tertiary: "#3d4547",
        "tertiary-container": "#555c5e",
      },
      spacing: {
        "gutter-grid": "12px",
        "margin-page": "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "inset-card": "16px",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      boxShadow: {
        soft: "0 4px 12px rgba(0, 0, 0, 0.05)",
        subtle: "0 2px 8px rgba(0, 0, 0, 0.02)",
        premium: "0 10px 30px -10px rgba(6, 44, 48, 0.1)",
        "premium-hover": "0 20px 40px -10px rgba(6, 44, 48, 0.15)",
      },
      fontFamily: {
        sans: ["PingFang SC", "Public Sans", "sans-serif"],
      },
      fontSize: {
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "body-lg": ["17px", { lineHeight: "26px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "600", letterSpacing: "0.05em" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "500", letterSpacing: "0.02em" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "display-lg": ["30px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
